### ISSUE TITLE
focusing the text widget

### ISSUE THREAD

**Issue by Akuli** [ghazigamer/Flash-Text-Editor#3]
After pressing Ctrl+N I need to click the text widget before I can start typing

**Comment by GhaziDev** [comment]
fixed.

**Comment by Akuli** [comment]
Which commit fixed this? I can't find it from your commit history: https://github.com/ghazigamer/Flash-Text-Editor/commits/master

I suggest writing commit messages that allow you and other people to actually find something from the commit history. For example, "fix issue #3" would be a **lot** better than "files edited". Also, if you mention `#3` in the commit message, that commit will automatically show up in issue #3 on github.

**Comment by Akuli** [comment]
this was fixed in 9522575
