### ISSUE TITLE
menu items are not lined up

### ISSUE THREAD

**Issue by Akuli** [ghazigamer/Flash-Text-Editor#4]
I drew a red line to make it more obvious, but it's quite visible even without the red line:

![tmp](https://user-images.githubusercontent.com/18505570/95553370-18b56a00-0a17-11eb-8ab8-8950f89927d6.png)

You can e.g. specify `accelerator='Ctrl+c'` when creating a menu item instead of giving it a label with lots of spaces in it.

**Comment by GhaziDev** [comment]
Fixed.
