### ISSUE TITLE
setup.py should be renamed to run.py

### ISSUE THREAD

**Issue by Akuli** [ghazigamer/Flash-Text-Editor#6]
In the Python community, the filename `setup.py` has a very special meaning, which is not what this project's `setup.py` does.

**Comment by GhaziDev** [comment]
i would like an explanation about the difference between "setup" and "run" in this case

**Comment by Akuli** [comment]
`setup.py` is the name of file for installing your program: https://stackoverflow.com/q/1471994

If you have a file that does something else, it should not be called `setup.py`.

**Comment by GhaziDev** [comment]
Thank you, fixed.
