### ISSUE TITLE
import style

### ISSUE THREAD

**Issue by Akuli** [ghazigamer/Flash-Text-Editor#7]
This project uses lots  of `from module import *`, which is almost always considered bad style in Python. Also, some files import things that they don't use. For example, `edit.py` imports `pyautogui` and does nothing with it.

I recommend checking the code with something like `flake8`. It gives a warning about both of these problems.

**Comment by GhaziDev** [comment]
thanks for ``flake8`` suggestion, fixed.

**Comment by Akuli** [comment]
Can you reopen this issue? It doesn't seem to be actually fixed. There are lots of star imports left, and flake8 says that there are also lots of unused imports:

```
edit.py:1:1: F401 'os' imported but unused
edit.py:2:1: F401 'tkinter.ttk' imported but unused
menubar.py:1:1: F401 'tkinter.ttk' imported but unused
right_click_menu.py:3:1: F401 'keyboard' imported but unused
run.py:1:1: F401 'tkinter.ttk' imported but unused
run.py:2:1: F401 'tkinter.*' imported but unused
run.py:5:1: F401 'tkinter.messagebox' imported but unused
search.py:3:1: F401 'keyboard' imported but unused
theme.py:2:1: F401 'tkinter.ttk' imported but unused
theme.py:5:1: F401 'search.Search' imported but unused
view.py:1:1: F401 'tkinter.ttk' imported but unused
```

**Comment by GhaziDev** [comment]
should be fixed from now, expect that flake8 will show warnings about "from tkinter import *", should i re-open the issue  then close it?

**Comment by Akuli** [comment]
Which flake8 version are you using? I just installed the latest flake8 (3.8.4) and I got a lot of warnings.

**Comment by GhaziDev** [comment]
![image](https://user-images.githubusercontent.com/46258765/103975207-76a14b80-51d8-11eb-9116-bbd167e1ac3f.png)
should be fixed by now, please test before i close this issue

**Comment by Akuli** [comment]
Nice. You might want to configure github actions so that it automatically runs flake8 every time you push a commit.
